service: update-n-rule

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2

functions:
  list:
    handler: handler.main
    events:
      - http:
          path: updateRule/{filename}
          method: put
          cors: true